In [1]:
import pandas as pd

Загрузим данные из файла

In [5]:
df = pd.read_excel('585.xlsx')

Проверим на актуальность типа данных

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139997 entries, 0 to 139996
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ДатаПродажи        139997 non-null  datetime64[ns]
 1   НомерЧека          139997 non-null  int64
 2   Номенклатура       139997 non-null  object
 3   Штрихкод           139997 non-null  int64
 4   ТоварнаяГруппа     139997 non-null  object
 5   СН_Характеристика  139996 non-null  object
 6   бгсВес             139997 non-null  float64
 7   ОбщаяСумма         139997 non-null  float64
 8   Себестоимость      139997 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(2), object(3)
memory usage: 9.6+ MB

In [10]:
df.head()

,ДатаПродажи,НомерЧека,Номенклатура,Штрихкод,ТоварнаяГруппа,СН_Характеристика,бгсВес,ОбщаяСумма,Себестоимость
0,2023-04-01 10:05:39,1814,серьги с брил.+изумрудом с родир,1078601904686,ДК СЕРЬГИ,Au 585º -,2.89,51180.0,17276.0475
1,2023-04-01 10:08:03,4868,Серьги с топазом,1078551306013,ПДК СЕРЬГИ,Au 585º -,3.99,34740.0,12074.7470
2,2023-04-01 10:08:23,617,Кольцо с брилл.+изум.гидротерм. с родир.,1078509166518,ДК КОЛЬЦА,"Au 585º -, разм.18,5",2.05,17760.0,6629.6120
3,2023-04-01 10:11:38,461,Кольцо с амет. род.,1078579406088,СИ КОЛЬЦО ЦВ/К,"Ag 925º -, разм.19,0",1.46,756.0,302.2200
4,2023-04-01 10:12:00,3939,Цепь Якорь с а/г род.,1078601866814,СИ ЦЕПЬ,"Ag 925º -, разм.40,0",2.70,1560.0,458.9995

Для начала отфильтруем данные по заданному периоду: с 1.04.23 по 10.04.23

In [24]:
df = df[(df['ДатаПродажи'] >= '2023-04-01') & (df['ДатаПродажи'] <= '2023-04-10')]

Оставим только данные изделий с общей суммой и себестоимостью больше 0 рублей

In [26]:
df = df[(df['ОбщаяСумма'] > 0) & (df['Себестоимость'] > 0)]

Вычислим наценку на ювелирные изделия и добавим столбец в датафрейм

In [28]:
df['Наценка'] = ((df['ОбщаяСумма'] - df['Себестоимость']) / df['Себестоимость']) * 100

In [30]:
df.head()

,ДатаПродажи,НомерЧека,Номенклатура,Штрихкод,ТоварнаяГруппа,СН_Характеристика,бгсВес,ОбщаяСумма,Себестоимость,Наценка
0,2023-04-01 10:05:39,1814,серьги с брил.+изумрудом с родир,1078601904686,ДК СЕРЬГИ,Au 585º -,2.89,51180.0,17276.0475,196.248317
1,2023-04-01 10:08:03,4868,Серьги с топазом,1078551306013,ПДК СЕРЬГИ,Au 585º -,3.99,34740.0,12074.7470,187.707892
2,2023-04-01 10:08:23,617,Кольцо с брилл.+изум.гидротерм. с родир.,1078509166518,ДК КОЛЬЦА,"Au 585º -, разм.18,5",2.05,17760.0,6629.6120,167.888981
3,2023-04-01 10:11:38,461,Кольцо с амет. род.,1078579406088,СИ КОЛЬЦО ЦВ/К,"Ag 925º -, разм.19,0",1.46,756.0,302.2200,150.148898
4,2023-04-01 10:12:00,3939,Цепь Якорь с а/г род.,1078601866814,СИ ЦЕПЬ,"Ag 925º -, разм.40,0",2.70,1560.0,458.9995,239.869651

Сгруппируем данные об изделиях по металлу

In [32]:
df_silver = df[df['ТоварнаяГруппа'].str.startswith('СИ')]
df_gold = df[~df['ТоварнаяГруппа'].str.startswith('СИ')]

In [34]:
df_silver.head()

,ДатаПродажи,НомерЧека,Номенклатура,Штрихкод,ТоварнаяГруппа,СН_Характеристика,бгсВес,ОбщаяСумма,Себестоимость,Наценка
3,2023-04-01 10:11:38,461,Кольцо с амет. род.,1078579406088,СИ КОЛЬЦО ЦВ/К,"Ag 925º -, разм.19,0",1.46,756.0,302.2200,150.148898
4,2023-04-01 10:12:00,3939,Цепь Якорь с а/г род.,1078601866814,СИ ЦЕПЬ,"Ag 925º -, разм.40,0",2.70,1560.0,458.9995,239.869651
5,2023-04-01 10:13:17,3194,Браслет с фиан. поз.,1078540181198,СИ БРАСЛЕТ СК,"Ag 925º -, разм.19,0",4.98,4622.4,1300.0290,255.561299
6,2023-04-01 10:13:17,3194,Серьги-продёвки поз.,1078568618163,СИ СЕРЬГИ РАЗН,Ag 925º -,3.53,3009.6,1022.9940,194.195274
8,2023-04-01 10:17:45,4689,Кольцо-печатка с черн.эмалью род.,1078601068378,СИ КОЛЬЦО ПЕЧАТ,"Ag 925º -, разм.21,0",4.07,3396.0,587.1555,478.381706

Посчитаем среднюю наценку для изделий из серебра

In [46]:
df_silver['Наценка'].mean()

216.59035699124053

In [36]:
df_gold.head()

,ДатаПродажи,НомерЧека,Номенклатура,Штрихкод,ТоварнаяГруппа,СН_Характеристика,бгсВес,ОбщаяСумма,Себестоимость,Наценка
0,2023-04-01 10:05:39,1814,серьги с брил.+изумрудом с родир,1078601904686,ДК СЕРЬГИ,Au 585º -,2.89,51180.0,17276.0475,196.248317
1,2023-04-01 10:08:03,4868,Серьги с топазом,1078551306013,ПДК СЕРЬГИ,Au 585º -,3.99,34740.0,12074.7470,187.707892
2,2023-04-01 10:08:23,617,Кольцо с брилл.+изум.гидротерм. с родир.,1078509166518,ДК КОЛЬЦА,"Au 585º -, разм.18,5",2.05,17760.0,6629.6120,167.888981
7,2023-04-01 10:17:27,6408,Браслет Лав пуст с а/г,1078567150945,ЦБ БРАСЛЕТЫ,"Au 585º -, разм.17,0",0.88,5748.0,2626.1170,118.878291
9,2023-04-01 10:18:18,3561,Цепь Ромб тройной пуст,1078601144359,ЦБ ЦЕПИ,"Au 585º -, разм.50,0",6.58,37500.0,20642.6035,81.663132

Посчитаем среднюю наценку для изделий из золота

In [48]:
df_gold['Наценка'].mean()

157.71144741508803